<Project Sdk="Microsoft.NET.Sdk">

  <!-- Project -->
	<PropertyGroup Label="project">
		<TargetFrameworks>netstandard2.1</TargetFrameworks>
		<LangVersion>14</LangVersion>
		<Nullable>enable</Nullable>

		<AssemblyName>OwlDomain.Common</AssemblyName>
		<RootNamespace>OwlDomain.Common</RootNamespace>
		<Version>2.1.0</Version>

		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<Deterministic>true</Deterministic>

		<EnableNETAnalyzers>true</EnableNETAnalyzers>
		<EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>

		<IsAotCompatible Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net7.0'))">true</IsAotCompatible>
		<IsTrimmable Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net6.0'))">true</IsTrimmable>
	</PropertyGroup>

	<!-- NuGet package -->
	<PropertyGroup Label="nuget">
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>

		<Authors>OwlDomain</Authors>
		<Copyright>Copyright (c) OwlDomain 2026 - $([System.DateTime]::UtcNow.Year)</Copyright>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>

		<RepositoryUrl>https://github.com/Owl-Domain/common-cs.git</RepositoryUrl>
		<PackageProjectUrl>https://www.github.com/Owl-Domain/common-cs</PackageProjectUrl>

		<PackageReadmeFile>readme.md</PackageReadmeFile>
		<PackageIcon>icon.png</PackageIcon>
		<PackageReleaseNotes>$([System.IO.File]::ReadAllText("$(MSBuildProjectDirectory)/meta/changelog.md"))</PackageReleaseNotes>

		<Description>This project contains various C#/.NET utilities that make things just a bit simpler.</Description>
		<PackageTags>common utilities</PackageTags>
	</PropertyGroup>

	<!-- Package files -->
	<ItemGroup Label="content">
		<None Pack="true" PackagePath="" Include="../icon.png" Link="meta/icon.png" />
		<None Pack="true" PackagePath="" Include="meta/readme.md" />
		<None Pack="true" PackagePath="" Include="meta/changelog.md" />
	</ItemGroup>

	<!-- Package references -->
	<ItemGroup Label="packages">
		<PackageReference Include="CommunityToolkit.Diagnostics" Version="8.4.2" />
	</ItemGroup>

</Project>
